---
- hosts: all
  become: true
  tasks:
  - name: install java
    yum:
     name: java
     state : present
  - name: download the tomcat binararies
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
      dest: /opt
  - name: untar
    unarchive:
      src: /opt/apache-tomcat-9.0.70.tar.gz
      dest: /opt/
      remote_src: true
  - name: rename
    command: mv /opt/apache-tomcat-9.0.70 /opt/tomcat
  - name: start
    shell: nohup /opt/tomcat/bin/startup.sh
